SELECT
  t1.TABLE_NAME AS "Table name",
  t1.COLUMN_NAME AS "Field name",
  CASE DATA_TYPE
    WHEN 'char'       THEN DATA_TYPE  + '(' + CASE CAST(CHARACTER_MAXIMUM_LENGTH AS VARCHAR) WHEN '-1' THEN 'max' ELSE CAST(CHARACTER_MAXIMUM_LENGTH AS VARCHAR) END + ')'
    WHEN 'numeric'    THEN DATA_TYPE  + '(' + CASE CAST(CHARACTER_MAXIMUM_LENGTH AS VARCHAR) WHEN '-1' THEN 'max' ELSE CAST(CHARACTER_MAXIMUM_LENGTH AS VARCHAR) END + ')'
    WHEN 'nvarchar'   THEN DATA_TYPE  + '(' + CASE CAST(CHARACTER_MAXIMUM_LENGTH AS VARCHAR) WHEN '-1' THEN 'max' ELSE CAST(CHARACTER_MAXIMUM_LENGTH AS VARCHAR) END + ')'
    WHEN 'varbinary'  THEN DATA_TYPE + '(' + CASE CAST(CHARACTER_MAXIMUM_LENGTH AS VARCHAR) WHEN '-1' THEN 'max' ELSE CAST(CHARACTER_MAXIMUM_LENGTH AS VARCHAR) END + ')'
    WHEN 'varchar'    THEN DATA_TYPE   + '(' + CASE CAST(CHARACTER_MAXIMUM_LENGTH AS VARCHAR) WHEN '-1' THEN 'max' ELSE CAST(CHARACTER_MAXIMUM_LENGTH AS VARCHAR) END + ')'
    ELSE DATA_TYPE
  END AS "Data type",
  LEFT(IS_NULLABLE,1)  "Is nullable",
  ISNULL((
    SELECT 
    CASE WHEN K.CONSTRAINT_NAME IS NULL THEN '' ELSE 'Y' END
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS C
    JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS K
    ON C.TABLE_NAME = K.TABLE_NAME
    AND C.CONSTRAINT_CATALOG = K.CONSTRAINT_CATALOG
    AND C.CONSTRAINT_SCHEMA = K.CONSTRAINT_SCHEMA
    AND C.CONSTRAINT_NAME = K.CONSTRAINT_NAME
    WHERE C.CONSTRAINT_TYPE = 'PRIMARY KEY' AND K.TABLE_NAME = t1.TABLE_NAME AND K.COLUMN_NAME = t1.COLUMN_NAME
  ), '') PK,
  ISNULL((
    select tab2.name
    FROM sys.foreign_key_columns fkc
    INNER JOIN sys.tables tab1 ON tab1.object_id = fkc.parent_object_id
    INNER JOIN sys.tables tab2 ON tab2.object_id = fkc.referenced_object_id
    INNER JOIN sys.columns col1 ON col1.column_id = parent_column_id AND col1.object_id = tab1.object_id
    WHERE tab1.name = t1.TABLE_NAME AND col1.name = t1.COLUMN_NAME
  ), '') AS [References],
  ISNULL((
    SELECT CASE WHEN df.definition IS NULL THEN '' ELSE 'DEFAULT' + df.definition END --df.definition
    FROM sys.default_constraints df
    INNER JOIN sys.tables t ON df.parent_object_id = t.object_id
    INNER JOIN sys.columns c ON c.object_id = df.parent_object_id AND df.parent_column_id = c.column_id
    WHERE t.name = t1.TABLE_NAME AND c.name = t1.COLUMN_NAME
  ), '') Constraints,
  '' AS "Description"
FROM [INFORMATION_SCHEMA].[COLUMNS] t1
  LEFT JOIN [INFORMATION_SCHEMA].[KEY_COLUMN_USAGE] pk
  ON(t1.TABLE_CATALOG = pk.TABLE_CATALOG
    AND t1.TABLE_SCHEMA = pk.TABLE_SCHEMA
    AND t1.TABLE_NAME = pk.TABLE_NAME
    AND t1.COLUMN_NAME = pk.COLUMN_NAME
    AND OBJECTPROPERTY(OBJECT_ID(pk.CONSTRAINT_SCHEMA + '.' + pk.CONSTRAINT_NAME), 'IsPrimaryKey') = 1)
  LEFT JOIN [INFORMATION_SCHEMA].[KEY_COLUMN_USAGE] fk
  ON(t1.TABLE_CATALOG = fk.TABLE_CATALOG
    AND t1.TABLE_SCHEMA = fk.TABLE_SCHEMA
    AND t1.TABLE_NAME = fk.TABLE_NAME
    AND t1.COLUMN_NAME = fk.COLUMN_NAME
    AND OBJECTPROPERTY(OBJECT_ID(fk.CONSTRAINT_SCHEMA + '.' + fk.CONSTRAINT_NAME), 'IsForeignKey') = 1)
order by t1.table_name
;